select * from restaurants;

-- List the top 5 cucisines as per revenue generated by top 5 resraurants of every cuisine

select cuisine, sum(cost*rating_count) as 'revenue' from 
 (select *, cost*rating_count as 'Revenue',
 row_number() over(partition by cuisine order by cost*rating_count desc) as 'Rank' 
 from restaurants)t where t.rank<6 group by cuisine order by Revenue desc Limit 5;

-- what % of total revenue is generated by top 1% restaurants

select sum(cost*rating_count) as 'Top 1 % Revenue' from  
	(Select *, cost*rating_count as 'Revenue', row_number() over(order by cost*rating_count desc) as 'rank' from restaurants) t
    where t.rank <= (select count(*)/100 from restaurants);

select sum(cost*rating_count) as 'Total Revenue' from  restaurants;


-- what % of revenue is generated by top 20 restaurants with respet to total revenue;

with 
 q1 as (select sum(cost*rating_count) as 'Top_20_Revenue' from  
	(Select *, cost*rating_count as 'Revenue', row_number() over(order by cost*rating_count desc) as 'rank' from restaurants) t
    where t.rank <= (select count(*)/100*20 from restaurants)),
q2 as (select sum(cost*rating_count) as 'Total_Revenue' from  restaurants)

select (Top_20_Revenue/Total_Revenue)*100 as 'Revenue %' from q1,q2;

